site_name: Perinola Framework
site_description: Revolutionary agile framework with rotating roles - boost team collaboration, shared ownership, and dynamic leadership. Perfect for modern distributed teams.
site_url: https://xe-nvdk.github.io/perinola-framework/
site_author: Ignacio Van Droogenbroeck

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xe-nvdk/perinola-framework
  generator: false

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

nav:
  - Home: index.md
  - What is Perinola?: what-is-perinola.md
  - The Six Spins: the-six-spins.md
  - Getting Started: getting-started.md
  - Implementation Guide: implementation-guide.md

plugins:
  - search:
      lang: en
  - meta

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - meta
  - attr_list
  - pymdownx.snippets